[package]
name = "njord"
version = "0.1.0"
authors = ["Victor Palade <victor.palade@dectris.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "=0.3.0-alpha.18"
failure = "0.1.5"
tokio = "=0.2.0-alpha.4"