
[package]
name = "njord"
version = "0.1.0"
authors = ["Victor Palade <victor@cloudflavor.io>"]
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
serde = "1.0.99"
serde_derive = "1.0.99"
clap = "2.33.0"
config = "0.9.3"
env_logger = "0.6.2"
log = "0.4.8"
tokio = {version = "0.2", features = ["full"]}
protobuf = { version = "2", features = ["with-bytes"] }

[build-dependencies]
protoc-rust = "2.0"
