on: [push]

name: Rust

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get protoc
      run: curl -OL  https://github.com/protocolbuffers/protobuf/releases/download/v3.9.2/protoc-3.9.2-linux-x86_64.zip

    - name: unzip
      run: unzip protoc-3.9.2-linux-x86_64.zip -d /usr/local/bin/protoc

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly

    - uses: actions/checkout@master

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
